var donnees = [
    {
        "Maillot": "23",
        "Joueur": "Yacine BAMMOU",
        "Poste": "Attaquant",
        "Age": "23",
        "Taille": "1.88",
        "Poids": "78",
        "temps_de_jeu_Pourcentage": "0.6645061728",
        "Note_sans_temps_de_jeu": "7.956229508",
        "Note_avec_tps_jeu": "25.50454584",
        "Ballons_Joués": "1109",
        "Temps_jeu": "2153",
        "Participation": "35",
        "Titulaire": "23",
        "Remplaçant": "12",
        "pourcentage_des_buts_du_FCN": "14",
        "Buts_marqués": "4",
        "Hors_jeu": "20",
        "Passes_décisives": "2",
        "Tirs": "61",
        "Tirs_cadrés": "18",
        "pourcentage_Tirs_Cadrés": "29.50819672",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "13",
        "Joueur": "Serge GAKPE",
        "Poste": "Attaquant",
        "Age": "27",
        "Taille": "1.76",
        "Poids": "68",
        "temps_de_jeu_Pourcentage": "0.6425925926",
        "Note_sans_temps_de_jeu": "8.27",
        "Note_avec_tps_jeu": "25.06677778",
        "Ballons_Joués": "958",
        "Temps_jeu": "2082",
        "Participation": "31",
        "Titulaire": "23",
        "Remplaçant": "8",
        "pourcentage_des_buts_du_FCN": "11",
        "Buts_marqués": "3",
        "Hors_jeu": "16",
        "Passes_décisives": "2",
        "Tirs": "50",
        "Tirs_cadrés": "18",
        "pourcentage_Tirs_Cadrés": "36",
        "Cartons_jaunes": "7",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "21",
        "Joueur": "Johan AUDEL",
        "Poste": "Attaquant",
        "Age": "31",
        "Taille": "1.80",
        "Poids": "75",
        "temps_de_jeu_Pourcentage": "0.3348765432",
        "Note_sans_temps_de_jeu": "7.319565217",
        "Note_avec_tps_jeu": "15.16999195",
        "Ballons_Joués": "568",
        "Temps_jeu": "1085",
        "Participation": "22",
        "Titulaire": "12",
        "Remplaçant": "10",
        "pourcentage_des_buts_du_FCN": "7",
        "Buts_marqués": "2",
        "Hors_jeu": "4",
        "Passes_décisives": "1",
        "Tirs": "23",
        "Tirs_cadrés": "9",
        "pourcentage_Tirs_Cadrés": "39.13043478",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "11",
        "Joueur": "Ismaël BANGOURA",
        "Poste": "Attaquant",
        "Age": "30",
        "Taille": "1.74",
        "Poids": "75",
        "temps_de_jeu_Pourcentage": "0.2049382716",
        "Note_sans_temps_de_jeu": "6.714545455",
        "Note_avec_tps_jeu": "10.84832997",
        "Ballons_Joués": "222",
        "Temps_jeu": "664",
        "Participation": "13",
        "Titulaire": "9",
        "Remplaçant": "4",
        "pourcentage_des_buts_du_FCN": "4",
        "Buts_marqués": "1",
        "Hors_jeu": "15",
        "Passes_décisives": "0",
        "Tirs": "11",
        "Tirs_cadrés": "4",
        "pourcentage_Tirs_Cadrés": "36.36363636",
        "Cartons_jaunes": "1",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "27",
        "Joueur": "Adama NIANE",
        "Poste": "Attaquant",
        "Age": "21",
        "Taille": "1.81",
        "Poids": "71",
        "temps_de_jeu_Pourcentage": "0.02037037037",
        "Note_sans_temps_de_jeu": "0.05",
        "Note_avec_tps_jeu": "0.6461111111",
        "Ballons_Joués": "24",
        "Temps_jeu": "66",
        "Participation": "3",
        "Titulaire": "0",
        "Remplaçant": "3",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "1",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "38",
        "Joueur": "Aristote NDONGALA",
        "Poste": "Attaquant",
        "Age": "21",
        "Taille": "1.74",
        "Poids": "68",
        "temps_de_jeu_Pourcentage": "0.01388888889",
        "Note_sans_temps_de_jeu": "0",
        "Note_avec_tps_jeu": "0.4166666667",
        "Ballons_Joués": "30",
        "Temps_jeu": "45",
        "Participation": "1",
        "Titulaire": "0",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "4",
        "Joueur": "Oswaldo VIZCARRONDO",
        "Poste": "Défenseur",
        "Age": "30",
        "Taille": "1.91",
        "Poids": "86",
        "temps_de_jeu_Pourcentage": "0.9719135802",
        "Note_sans_temps_de_jeu": "402.28",
        "Note_avec_tps_jeu": "310.7534074",
        "Ballons_Joués": "1195",
        "Temps_jeu": "3149",
        "Participation": "35",
        "Titulaire": "35",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "7",
        "Buts_marqués": "2",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "17",
        "Tirs_cadrés": "7",
        "pourcentage_Tirs_Cadrés": "41.17647059",
        "Cartons_jaunes": "5",
        "Cartons_rouges": "1",
        "Ballons_perdus": "369",
        "Ballons_gagnés": "417"
    },
    {
        "Maillot": "22",
        "Joueur": "Issa CISSOKHO",
        "Poste": "Défenseur",
        "Age": "30",
        "Taille": "1.71",
        "Poids": "68",
        "temps_de_jeu_Pourcentage": "0.8611111111",
        "Note_sans_temps_de_jeu": "471.05",
        "Note_avec_tps_jeu": "355.5683333",
        "Ballons_Joués": "1875",
        "Temps_jeu": "2790",
        "Participation": "31",
        "Titulaire": "31",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "7",
        "Tirs_cadrés": "1",
        "pourcentage_Tirs_Cadrés": "14.28571429",
        "Cartons_jaunes": "5",
        "Cartons_rouges": "0",
        "Ballons_perdus": "466",
        "Ballons_gagnés": "380"
    },
    {
        "Maillot": "3",
        "Joueur": "Papy Mison DJILOBODJI",
        "Poste": "Défenseur",
        "Age": "26",
        "Taille": "1.93",
        "Poids": "82",
        "temps_de_jeu_Pourcentage": "0.7827160494",
        "Note_sans_temps_de_jeu": "444.9",
        "Note_avec_tps_jeu": "334.9114815",
        "Ballons_Joués": "1284",
        "Temps_jeu": "2536",
        "Participation": "29",
        "Titulaire": "28",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "24",
        "Tirs_cadrés": "6",
        "pourcentage_Tirs_Cadrés": "25",
        "Cartons_jaunes": "10",
        "Cartons_rouges": "0",
        "Ballons_perdus": "374",
        "Ballons_gagnés": "482"
    },
    {
        "Maillot": "2",
        "Joueur": "Kian HANSEN",
        "Poste": "Défenseur",
        "Age": "26",
        "Taille": "1.84",
        "Poids": "74",
        "temps_de_jeu_Pourcentage": "0.7441358025",
        "Note_sans_temps_de_jeu": "376.41",
        "Note_avec_tps_jeu": "285.8110741",
        "Ballons_Joués": "1189",
        "Temps_jeu": "2411",
        "Participation": "29",
        "Titulaire": "28",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "1",
        "Tirs": "19",
        "Tirs_cadrés": "1",
        "pourcentage_Tirs_Cadrés": "5.263157895",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "0",
        "Ballons_perdus": "314",
        "Ballons_gagnés": "389"
    },
    {
        "Maillot": "5",
        "Joueur": "Olivier VEIGNEAU",
        "Poste": "Défenseur",
        "Age": "29",
        "Taille": "1.74",
        "Poids": "65",
        "temps_de_jeu_Pourcentage": "0.5762345679",
        "Note_sans_temps_de_jeu": "355.44",
        "Note_avec_tps_jeu": "266.095037",
        "Ballons_Joués": "1213",
        "Temps_jeu": "1867",
        "Participation": "22",
        "Titulaire": "22",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "3",
        "Tirs_cadrés": "1",
        "pourcentage_Tirs_Cadrés": "33.33333333",
        "Cartons_jaunes": "2",
        "Cartons_rouges": "0",
        "Ballons_perdus": "380",
        "Ballons_gagnés": "316"
    },
    {
        "Maillot": "24",
        "Joueur": "Chaker ALHADHUR",
        "Poste": "Défenseur",
        "Age": "23",
        "Taille": "1.72",
        "Poids": "65",
        "temps_de_jeu_Pourcentage": "0.3404320988",
        "Note_sans_temps_de_jeu": "198.04",
        "Note_avec_tps_jeu": "148.840963",
        "Ballons_Joués": "785",
        "Temps_jeu": "1103",
        "Participation": "15",
        "Titulaire": "12",
        "Remplaçant": "3",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "7",
        "Tirs_cadrés": "4",
        "pourcentage_Tirs_Cadrés": "57.14285714",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "1",
        "Ballons_perdus": "171",
        "Ballons_gagnés": "170"
    },
    {
        "Maillot": "26",
        "Joueur": "Koffi DJIDJI",
        "Poste": "Défenseur",
        "Age": "22",
        "Taille": "1.84",
        "Poids": "71",
        "temps_de_jeu_Pourcentage": "0.08364197531",
        "Note_sans_temps_de_jeu": "39.77",
        "Note_avec_tps_jeu": "30.34825926",
        "Ballons_Joués": "107",
        "Temps_jeu": "271",
        "Participation": "4",
        "Titulaire": "3",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "1",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "1",
        "Cartons_rouges": "0",
        "Ballons_perdus": "35",
        "Ballons_gagnés": "44"
    },
    {
        "Maillot": "15",
        "Joueur": "Léo DUBOIS",
        "Poste": "Défenseur",
        "Age": "20",
        "Taille": "1.78",
        "Poids": "66",
        "temps_de_jeu_Pourcentage": "0.002469135802",
        "Note_sans_temps_de_jeu": "0.2",
        "Note_avec_tps_jeu": "0.2140740741",
        "Ballons_Joués": "2",
        "Temps_jeu": "8",
        "Participation": "1",
        "Titulaire": "0",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "1",
        "Joueur": "Rémy RIOU",
        "Poste": "Gardien",
        "Age": "27",
        "Taille": "1.89",
        "Poids": "81",
        "temps_de_jeu_Pourcentage": "0.8333333333",
        "Note_sans_temps_de_jeu": "0",
        "Note_avec_tps_jeu": "25",
        "Ballons_Joués": "980",
        "Temps_jeu": "2700",
        "Participation": "30",
        "Titulaire": "30",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "30",
        "Joueur": "Maxime DUPE",
        "Poste": "Gardien",
        "Age": "22",
        "Taille": "1.86",
        "Poids": "87",
        "temps_de_jeu_Pourcentage": "0.1666666667",
        "Note_sans_temps_de_jeu": "0",
        "Note_avec_tps_jeu": "5",
        "Ballons_Joués": "177",
        "Temps_jeu": "540",
        "Participation": "6",
        "Titulaire": "6",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "25",
        "Joueur": "Jordan VERETOUT",
        "Poste": "Milieu",
        "Age": "22",
        "Taille": "1.76",
        "Poids": "66",
        "temps_de_jeu_Pourcentage": "0.9367283951",
        "Note_sans_temps_de_jeu": "589.0533333",
        "Note_avec_tps_jeu": "440.4391852",
        "Ballons_Joués": "1943",
        "Temps_jeu": "3035",
        "Participation": "34",
        "Titulaire": "34",
        "Remplaçant": "0",
        "pourcentage_des_buts_du_FCN": "25",
        "Buts_marqués": "7",
        "Hors_jeu": "0",
        "Passes_décisives": "4",
        "Tirs": "54",
        "Tirs_cadrés": "18",
        "pourcentage_Tirs_Cadrés": "33.33333333",
        "Cartons_jaunes": "5",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "18",
        "Joueur": "Lucas DEAUX",
        "Poste": "Milieu",
        "Age": "26",
        "Taille": "1.85",
        "Poids": "72",
        "temps_de_jeu_Pourcentage": "0.6179012346",
        "Note_sans_temps_de_jeu": "409.4254545",
        "Note_avec_tps_jeu": "305.1348552",
        "Ballons_Joués": "1349",
        "Temps_jeu": "2002",
        "Participation": "32",
        "Titulaire": "22",
        "Remplaçant": "10",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "11",
        "Tirs_cadrés": "5",
        "pourcentage_Tirs_Cadrés": "45.45454545",
        "Cartons_jaunes": "6",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "7",
        "Joueur": "Alejandro BEDOYA",
        "Poste": "Milieu",
        "Age": "28",
        "Taille": "1.78",
        "Poids": "73",
        "temps_de_jeu_Pourcentage": "0.5827160494",
        "Note_sans_temps_de_jeu": "292.1471429",
        "Note_avec_tps_jeu": "221.9844815",
        "Ballons_Joués": "961",
        "Temps_jeu": "1888",
        "Participation": "28",
        "Titulaire": "20",
        "Remplaçant": "8",
        "pourcentage_des_buts_du_FCN": "11",
        "Buts_marqués": "3",
        "Hors_jeu": "0",
        "Passes_décisives": "1",
        "Tirs": "35",
        "Tirs_cadrés": "10",
        "pourcentage_Tirs_Cadrés": "28.57142857",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "8",
        "Joueur": "Vincent BESSAT",
        "Poste": "Milieu",
        "Age": "29",
        "Taille": "1.73",
        "Poids": "60",
        "temps_de_jeu_Pourcentage": "0.4987654321",
        "Note_sans_temps_de_jeu": "332.7215789",
        "Note_avec_tps_jeu": "247.8680682",
        "Ballons_Joués": "1100",
        "Temps_jeu": "1616",
        "Participation": "27",
        "Titulaire": "19",
        "Remplaçant": "8",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "19",
        "Tirs_cadrés": "5",
        "pourcentage_Tirs_Cadrés": "26.31578947",
        "Cartons_jaunes": "3",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "14",
        "Joueur": "Georges-Kévin NKOUDOU",
        "Poste": "Milieu",
        "Age": "20",
        "Taille": "1.72",
        "Poids": "68",
        "temps_de_jeu_Pourcentage": "0.4811728395",
        "Note_sans_temps_de_jeu": "227.3637037",
        "Note_avec_tps_jeu": "173.5897778",
        "Ballons_Joués": "743",
        "Temps_jeu": "1559",
        "Participation": "26",
        "Titulaire": "16",
        "Remplaçant": "10",
        "pourcentage_des_buts_du_FCN": "7",
        "Buts_marqués": "2",
        "Hors_jeu": "0",
        "Passes_décisives": "1",
        "Tirs": "27",
        "Tirs_cadrés": "10",
        "pourcentage_Tirs_Cadrés": "37.03703704",
        "Cartons_jaunes": "2",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "6",
        "Joueur": "Rémi GOMIS",
        "Poste": "Milieu",
        "Age": "31",
        "Taille": "1.80",
        "Poids": "74",
        "temps_de_jeu_Pourcentage": "0.3611111111",
        "Note_sans_temps_de_jeu": "198.11",
        "Note_avec_tps_jeu": "149.5103333",
        "Ballons_Joués": "651",
        "Temps_jeu": "1170",
        "Participation": "19",
        "Titulaire": "14",
        "Remplaçant": "5",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "4",
        "Tirs_cadrés": "1",
        "pourcentage_Tirs_Cadrés": "25",
        "Cartons_jaunes": "8",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "28",
        "Joueur": "Valentin RONGIER",
        "Poste": "Milieu",
        "Age": "20",
        "Taille": "1.72",
        "Poids": "66",
        "temps_de_jeu_Pourcentage": "0.04444444444",
        "Note_sans_temps_de_jeu": "35.73",
        "Note_avec_tps_jeu": "26.34433333",
        "Ballons_Joués": "93",
        "Temps_jeu": "144",
        "Participation": "4",
        "Titulaire": "1",
        "Remplaçant": "3",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "1",
        "Tirs": "4",
        "Tirs_cadrés": "3",
        "pourcentage_Tirs_Cadrés": "75",
        "Cartons_jaunes": "1",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "20",
        "Joueur": "Jules ILOKI",
        "Poste": "Milieu",
        "Age": "23",
        "Taille": "1.72",
        "Poids": "69",
        "temps_de_jeu_Pourcentage": "0.008641975309",
        "Note_sans_temps_de_jeu": "5.4",
        "Note_avec_tps_jeu": "4.039259259",
        "Ballons_Joués": "18",
        "Temps_jeu": "28",
        "Participation": "2",
        "Titulaire": "0",
        "Remplaçant": "2",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    },
    {
        "Maillot": "12",
        "Joueur": "Birama TOURE",
        "Poste": "Milieu",
        "Age": "22",
        "Taille": "1.83",
        "Poids": "75",
        "temps_de_jeu_Pourcentage": "0.0009259259259",
        "Note_sans_temps_de_jeu": "0",
        "Note_avec_tps_jeu": "0.02777777778",
        "Ballons_Joués": "0",
        "Temps_jeu": "3",
        "Participation": "1",
        "Titulaire": "0",
        "Remplaçant": "1",
        "pourcentage_des_buts_du_FCN": "0",
        "Buts_marqués": "0",
        "Hors_jeu": "0",
        "Passes_décisives": "0",
        "Tirs": "0",
        "Tirs_cadrés": "0",
        "pourcentage_Tirs_Cadrés": "0",
        "Cartons_jaunes": "0",
        "Cartons_rouges": "0",
        "Ballons_perdus": "0",
        "Ballons_gagnés": "0"
    }
];